
/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: 2026-07-26T08:29:17.453Z
 */

export type NetworkName = 'ethereum';
export type ProtocolName = 'velora';

export const bundle: string;
