
/**
 * WDK Bundle TypeScript Declarations
 * Generated by @tetherto/wdk-worklet-bundler
 * Generated at: 2026-07-26T12:34:03.412Z
 */

export type NetworkName = 'ethereum';
export type ProtocolName = 'velora';

export const bundle: string;
